# Generated by Django 5.1.5 on 2025-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0002_prdata_internal_counter_party_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdata',
            name='internal_counter_party_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='internal_field_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='internal_field_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='internal_field_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='internal_field_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='internal_field_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='internal_reference_document_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='plant_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
