# Generated by Django 5.1.5 on 2025-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0003_alter_prdata_internal_counter_party_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationreport',
            name='vendor_communication_status',
            field=models.BooleanField(default=False),
        ),
    ]
