# Generated by Django 5.1.5 on 2025-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0003_alter_prdata_internal_counter_party_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdatatransactions',
            name='upload_period',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdatatransactions',
            name='upload_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
