# Generated by Django 5.1.5 on 2025-06-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0004_prdatatransactions_upload_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdata',
            name='guid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prdata',
            name='upload_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prdata',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Sandbox2bDataResponse',
        ),
    ]
