# Generated by Django 5.1.5 on 2025-06-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0005_prdata_guid_prdata_upload_type_prdata_voucher_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdatatransactions',
            name='upload_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prdatatransactions',
            name='upload_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
