# Generated by Django 5.1.5 on 2025-06-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0006_alter_prdatatransactions_upload_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdata',
            name='upload_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
