# Generated by Django 5.1.5 on 2025-06-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0007_alter_prdata_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdatatransactions',
            name='filename',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='prdatatransactions',
            name='s3_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
