# Generated by Django 5.1.5 on 2025-06-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0008_alter_prdatatransactions_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdatatransactions',
            name='validation_error_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
