# Generated by Django 5.0.3 on 2025-06-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0004_reconciliationreport_vendor_communication_status"),
        ("gst", "0008_alter_prdatatransactions_filename_and_more"),
    ]

    operations = []
