# Generated by Django 5.1.5 on 2025-06-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0009_alter_prdatatransactions_validation_error_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdatatransactions',
            name='validation_error_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Failure'), (0, 'Success'), (2, 'Transaction Failed')], null=True),
        ),
    ]
