# Generated by Django 5.0.3 on 2025-06-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0009_merge_20250624_0904"),
        ("gst", "0010_alter_prdatatransactions_validation_error_status"),
    ]

    operations = []
