# Generated by Django 5.1.5 on 2025-07-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0011_merge_20250627_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdata',
            name='voucher_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
