# Generated by Django 5.1.5 on 2025-07-14 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_usergstinfo_gst_token'),
        ('gst', '0013_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.CharField(choices=[('reconciliation', 'Reconciliation'), ('data_2b_fetch', 'GSTR-2B Fetch'), ('zoho_fetch', 'Zoho Data Fetch'), ('tally_fetch', 'Tally Data Fetch')], help_text="The specific module within the app (e.g., 'reconciliation', 'data_2b_fetch').", max_length=50)),
                ('title', models.CharField(help_text='A concise title for the notification.', max_length=255)),
                ('message', models.TextField(help_text='The main content or details of the notification.')),
                ('type', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('info', 'Info'), ('warning', 'Warning')], default='info', help_text='The type/severity of the notification.', max_length=20)),
                ('priority', models.CharField(default='normal', help_text='The priority level of the notification.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional key-value pairs related to the notification (e.g., financial_year, quarter, months, status, record_count).', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time when the notification was created.')),
                ('read', models.BooleanField(default=False, help_text='Indicates if the notification has been read by the user.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification should expire.', null=True)),
                ('thread_id', models.CharField(blank=True, help_text='Identifier to group related notifications.', max_length=255, null=True)),
                ('action_type', models.CharField(blank=True, max_length=255, null=True)),
                ('action_label', models.CharField(blank=True, max_length=255, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('action_app', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
                ('user_gst_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gst_notifications', to='authentication.usergstinfo')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
