# Generated by Django 5.1.5 on 2025-07-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0014_notifications_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdata',
            name='duplicate_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prdata',
            name='validation_error_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='prdatatransactions',
            name='upload_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prdatatransactions',
            name='upload_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='timerange',
            name='status_data_edited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='timerange',
            name='status_validation_errors',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Accounting_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='CGST',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Cess',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Document_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='GSTIN_of_Supplier',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='GSTIN_of_User',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='IGST',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Invoice_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Name_of_Supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Return_Period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='SGST',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Supplier_Invoice_Date_or_Note_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Supplier_Invoice_Number_or_Note_Number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='Taxable_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='prdata',
            name='reconciliation_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
