# Generated by Django 5.1.5 on 2025-07-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0015_prdata_duplicate_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdatatransactions',
            old_name='upload_status',
            new_name='upload_error_status',
        ),
    ]
