# Generated by Django 5.1.5 on 2025-07-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0016_rename_upload_status_prdatatransactions_upload_error_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdata',
            name='duplicate_errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prdata',
            name='validation_errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
