# Generated by Django 5.1.5 on 2025-07-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0017_rename_data_edited_status_timerange_status_data_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdata',
            name='validation_errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
