# Generated by Django 5.1.5 on 2025-07-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0018_remove_timerange_data_edited_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdata',
            old_name='GSTIN_of_Supplier',
            new_name='supplier_gstin',
        )
    ]
