# Generated by Django 5.1.5 on 2025-07-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0019_rename_gstin_of_supplier_prdata_supplier_gstin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdata',
            old_name='Document_Type',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Inter_Intra',
            new_name='inter_intra',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Return_Period',
            new_name='return_period',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Name_of_Supplier',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='GSTIN_of_User',
            new_name='user_gstin',
        ),
    ]
