# Generated by Django 5.1.5 on 2025-07-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0020_rename_document_type_prdata_document_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdata',
            old_name='Accounting_Date',
            new_name='accounting_date',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Cess',
            new_name='cess',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='CGST',
            new_name='cgst',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Supplier_Invoice_Date_or_Note_Date',
            new_name='document_date',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Supplier_Invoice_Number_or_Note_Number',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='IGST',
            new_name='igst',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Invoice_Value',
            new_name='invoice_value',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Place_of_Supply',
            new_name='place_of_supply',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='SGST',
            new_name='sgst',
        ),
        migrations.RenameField(
            model_name='prdata',
            old_name='Taxable_Value',
            new_name='taxable_value',
        ),
    ]
