# Generated by Django 5.1.5 on 2025-07-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0021_rename_accounting_date_prdata_accounting_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prdata',
            old_name='user_gst_information',
            new_name='user_gst_info',
        ),
    ]
