# Generated by Django 5.1.5 on 2025-07-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0022_rename_user_gst_information_prdata_user_gst_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data2b',
            old_name='CGST',
            new_name='cgst',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Supplier_Invoice_Number_or_Note_Number',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='IGST',
            new_name='igst',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Section',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='SGST',
            new_name='sgst',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='GSTIN_of_Supplier',
            new_name='supplier_gstin',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Taxable_Value',
            new_name='taxable_value',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='user_gst_information',
            new_name='user_gst_info',
        ),
    ]
