# Generated by Django 5.1.5 on 2025-07-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0023_rename_cgst_data2b_cgst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data2b',
            old_name='Supplier_Invoice_Date_or_Note_Date',
            new_name='document_date',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Doc_Type',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Note_Supply_Type',
            new_name='note_supply_type',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Place_of_Supply',
            new_name='place_of_supply',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Return_Period',
            new_name='return_period',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Trade_or_Legal_name_of_Supplier',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='GSTIN_of_User',
            new_name='user_gstin',
        ),
        migrations.RenameField(
            model_name='timerange',
            old_name='user_gst_information',
            new_name='user_gst_info',
        ),
    ]
