# Generated by Django 5.1.5 on 2025-07-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0024_rename_supplier_invoice_date_or_note_date_data2b_document_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data2b',
            old_name='Applicable_Percent_of_Tax_Rate',
            new_name='applicable_percent_of_tax_rate',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Cess',
            new_name='cess',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Gst_Rate_Percent',
            new_name='gst_rate_percent',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Inter_or_Intra',
            new_name='inter_or_intra',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Invoice_Value',
            new_name='invoice_value',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='IRN',
            new_name='irn',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='IRN_Generated_Date',
            new_name='irn_generated_date',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='ITC_Availability',
            new_name='itc_availability',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Reason',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Supplier_Filing_date',
            new_name='supplier_filing_date',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Supplier_filing_period',
            new_name='supplier_filing_period',
        ),
        migrations.RenameField(
            model_name='data2b',
            old_name='Supply_attract_reverse_charge',
            new_name='supply_attract_reverse_charge',
        ),
    ]
