# Generated by Django 5.1.5 on 2025-07-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0025_rename_applicable_percent_of_tax_rate_data2b_applicable_percent_of_tax_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data2b',
            old_name='reason',
            new_name='itc_unavailability_reason',
        ),
    ]
