# Generated by Django 5.0.3 on 2024-11-12 17:58

import apps.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[apps.authentication.validators.user_name_validator],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[apps.authentication.validators.user_name_validator],
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Please provide plain text phone number. e.g:3102345678",
                        max_length=15,
                        null=True,
                        validators=[apps.authentication.validators.phone_validator],
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "image_path",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Please provide at least 2 words.",
                        max_length=300,
                        null=True,
                        validators=[apps.authentication.validators.address_validator],
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "db_table": "user",
                "ordering": ("first_name", "last_name"),
                "indexes": [
                    models.Index(fields=["-is_active"], name="user_is_acti_2beda7_idx")
                ],
            },
        ),
    ]
