# Generated by Django 5.0.3 on 2024-12-15 03:55

import apps.authentication.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_image_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150,
                        validators=[apps.authentication.validators.name_validator],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Please provide plain text phone number. e.g:3102345678",
                        max_length=15,
                        null=True,
                        validators=[apps.authentication.validators.phone_validator],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Please provide at least 2 words.",
                        max_length=300,
                        null=True,
                        validators=[apps.authentication.validators.address_validator],
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "db_table": "company",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="authentication.company",
            ),
        ),
    ]
