# Generated by Django 5.0.3 on 2024-12-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_company_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, null=True, unique=True
            ),
        ),
    ]
