# Generated by Django 5.0.3 on 2024-12-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_company_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.IntegerField(default=2),
        ),
    ]
