# Generated by Django 5.0.3 on 2024-12-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_credits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="credits",
        ),
    ]
