# Generated by Django 5.0.3 on 2025-01-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_gstinfo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GstInfo",
            new_name="UserGstInfo",
        ),
    ]
