# Generated by Django 5.0.3 on 2025-01-12 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_rename_gstinfo_usergstinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergstinfo",
            name="user_id",
        ),
        migrations.AddField(
            model_name="usergstinfo",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gst_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
