# Generated by Django 5.0.3 on 2025-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_remove_usergstinfo_user_id_usergstinfo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergstinfo",
            name="refreshed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
