# Generated by Django 5.1.4 on 2025-01-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_usergstinfo_refreshed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergstinfo",
            name="gst_number",
            field=models.CharField(default="default_value", max_length=500),
        ),
        migrations.AddField(
            model_name="usergstinfo",
            name="gst_username",
            field=models.CharField(default="default_value", max_length=500),
        ),
    ]
