# Generated by Django 5.0.3 on 2025-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_usergstinfo_refreshed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergstinfo",
            name="gstin",
            field=models.CharField(default="default_value", max_length=500),
        ),
    ]
