# Generated by Django 5.1.4 on 2025-01-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_usergstinfo_gst_number_usergstinfo_gst_username'),
    ]

    operations = [
        
    ]
