# Generated by Django 5.1.4 on 2025-02-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_passwordreset'),
        ('authentication', '0013_merge_20250120_0253'),
    ]

    operations = [
    ]
