# Generated by Django 5.1.5 on 2025-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_merge_0007_passwordreset_0013_merge_20250120_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergstinfo',
            name='company_name',
            field=models.CharField(default='default_value', max_length=500),
        ),
    ]
