# Generated by Django 5.1.5 on 2025-05-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_usergstinfo_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usergstinfo",
            name="gst_number",
        ),
    ]
