# Generated by Django 5.1.5 on 2025-05-22 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_remove_usergstinfo_gst_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_mobile_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserVerifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("otp", models.CharField(max_length=6)),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("mobile", "Mobile")],
                        max_length=10,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("expiry", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Verification",
                "db_table": "user_verification",
            },
        ),
    ]
