# Generated by Django 5.1.5 on 2025-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0017_user_is_email_verified_user_is_mobile_verified_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SuperAdmin", "SuperAdmin"),
                            ("Admin", "Admin"),
                            ("Maker", "Maker"),
                            ("Checker", "Checker"),
                            ("Approver", "Approver"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "role",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                db_table="user_roles",
                related_name="users",
                to="authentication.role",
            ),
        ),
    ]
