# Generated by Django 5.1.5 on 2025-07-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_role_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergstinfo",
            name="gst_token",
            field=models.TextField(),
        ),
    ]
